/// Generated by AssetsRefGenerator on 2022/04/20
class Res {
  static const String design_course = "assets/design_course/design_course.png";
  static const String interFace1 = "assets/design_course/interFace1.png";
  static const String interFace2 = "assets/design_course/interFace2.png";
  static const String interFace3 = "assets/design_course/interFace3.png";
  static const String interFace4 = "assets/design_course/interFace4.png";
  static const String Roboto_Bold = "assets/fonts/Roboto-Bold.ttf";
  static const String Roboto_Medium = "assets/fonts/Roboto-Medium.ttf";
  static const String Roboto_Regular = "assets/fonts/Roboto-Regular.ttf";
  static const String userImage = "assets/design_course/userImage.png";
  static const String webInterFace = "assets/design_course/webInterFace.png";
  static const String WorkSans_Bold = "assets/fonts/WorkSans-Bold.ttf";
  static const String WorkSans_Medium = "assets/fonts/WorkSans-Medium.ttf";
  static const String WorkSans_Regular = "assets/fonts/WorkSans-Regular.ttf";
  static const String WorkSans_SemiBold = "assets/fonts/WorkSans-SemiBold.ttf";
}
